{"message":{"error":"connect ECONNREFUSED 127.0.0.1:5432","stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at Client._connectionCallback (/home/jbolanyox/fit-exercise/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:172:24)\n    at Client._handleErrorWhileConnecting (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorEvent (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/client.js:315:19)\n    at Connection.emit (events.js:376:20)\n    at Socket.reportStreamError (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/connection.js:52:12)\n    at Socket.emit (events.js:376:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","date":"2021-06-22T16:19:02.586Z"},"level":"error","service":"user-service"}
{"message":{"error":"connect ECONNREFUSED 127.0.0.1:5432","stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at Client._connectionCallback (/home/jbolanyox/fit-exercise/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:172:24)\n    at Client._handleErrorWhileConnecting (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorEvent (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/client.js:315:19)\n    at Connection.emit (events.js:376:20)\n    at Socket.reportStreamError (/home/jbolanyox/fit-exercise/server/node_modules/pg/lib/connection.js:52:12)\n    at Socket.emit (events.js:376:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","date":"2021-06-22T16:19:47.811Z"},"level":"error","service":"user-service"}
